import { NextResponse } from "next/server";
import ExcelJS from "exceljs";
import { parseSubmissionFileName, type SubmissionDocType } from "@/lib/travel/submission-naming";
import { readJsonSheet } from "@/lib/travel/excel-embed";
import type { TravelClaimImportPayload } from "@/lib/travel/claim/types";
import type { TravelRequestImportPayload } from "@/lib/travel/types";

// Re-imports a previously system-generated Travel Claim OR Travel Request .xlsx to auto-fill a
// claim re-submission -- letting a user start their claim from the request they already filed for
// the same trip. The filename gates entry (must exactly match buildSubmissionFileName's TC or TR
// format); the embedded __data sheet (see lib/travel/excel-embed.ts) is the actual data source --
// never parsed cells. A TR source has no `travelArea` (Claim-only field, HIV team) -- left "" for
// the user to fill in, same as a blank manual entry; normal claim validation requires it where
// needed. Mirrors app/api/travel/import/route.ts (Travel Request's own importer, TR-only).

export const runtime = "nodejs";

const BAD_FILENAME_ERROR =
  "This doesn't look like a travel claim or travel request file generated by this system. Please upload the exact Excel the system produced.";
const NO_EMBEDDED_DATA_ERROR =
  "This file doesn't contain the data this system needs to re-import it (it may have been generated before this feature was added). Please re-enter the details manually.";
const CORRUPT_FILE_ERROR = "Couldn't read this Excel file — it may be corrupted. Please try uploading it again.";

export interface ImportClaimResponseBody {
  header: TravelClaimImportPayload["header"];
  trips: TravelClaimImportPayload["trips"];
  submissionNumber: number;
  sourceDocType: SubmissionDocType;
}

export async function POST(request: Request): Promise<NextResponse> {
  let file: File;
  try {
    const form = await request.formData();
    const f = form.get("file");
    if (!(f instanceof File)) {
      return NextResponse.json({ error: "No file provided" }, { status: 400 });
    }
    file = f;
  } catch {
    return NextResponse.json({ error: "Invalid request body" }, { status: 400 });
  }

  const parsedName = parseSubmissionFileName(file.name, "TC") ?? parseSubmissionFileName(file.name, "TR");
  if (!parsedName) {
    return NextResponse.json({ error: BAD_FILENAME_ERROR }, { status: 400 });
  }

  let wb: ExcelJS.Workbook;
  try {
    const buffer = Buffer.from(await file.arrayBuffer());
    wb = new ExcelJS.Workbook();
    // exceljs's own index.d.ts (line 1) declares a global `interface Buffer extends ArrayBuffer
    // {}`, which merges into -- and corrupts -- Node's real ambient Buffer type by additionally
    // demanding ArrayBuffer-only members (resizable/maxByteLength/etc, from modern lib.esnext)
    // that no real Buffer.from() result has. writeBuffer()'s return side is unaffected (Buffer.
    // from() accepts the wider ArrayBufferLike shape), but load()'s input side breaks for any
    // real Buffer -- an upstream typing bug, not a real runtime mismatch.
    // @ts-expect-error -- see comment above; buffer is a genuine Node Buffer at runtime.
    await wb.xlsx.load(buffer);
  } catch (e) {
    console.error("[claim-import] step=load error", e);
    return NextResponse.json({ error: CORRUPT_FILE_ERROR }, { status: 400 });
  }

  let header: ImportClaimResponseBody["header"];
  let trips: ImportClaimResponseBody["trips"];
  if (parsedName.docType === "TC") {
    const payload = readJsonSheet<TravelClaimImportPayload>(wb);
    if (!payload) {
      return NextResponse.json({ error: NO_EMBEDDED_DATA_ERROR }, { status: 422 });
    }
    header = payload.header;
    trips = payload.trips;
  } else {
    const payload = readJsonSheet<TravelRequestImportPayload>(wb);
    if (!payload) {
      return NextResponse.json({ error: NO_EMBEDDED_DATA_ERROR }, { status: 422 });
    }
    // Travel Request's payload has no travelArea (Claim-only, HIV team) -- left blank for the
    // user to fill in; normal claim validation requires it where needed (see validateClaimForm).
    header = { ...payload.header, travelArea: "" };
    trips = payload.trips;
  }

  const body: ImportClaimResponseBody = {
    header,
    trips,
    submissionNumber: parsedName.submissionNumber,
    sourceDocType: parsedName.docType,
  };
  return NextResponse.json(body);
}
