import { NextResponse } from "next/server";
import ExcelJS from "exceljs";
import { parseSubmissionFileName } from "@/lib/travel/submission-naming";
import { readJsonSheet } from "@/lib/travel/excel-embed";
import type { TravelRequestImportPayload } from "@/lib/travel/types";

// Re-imports a previously system-generated Travel Request .xlsx to auto-fill a re-submission.
// The filename gates entry (must exactly match buildSubmissionFileName's format); the embedded
// __data sheet (see lib/travel/excel-embed.ts) is the actual data source -- never parsed cells.

export const runtime = "nodejs";

const BAD_FILENAME_ERROR =
  "This doesn't look like a travel request file generated by this system. Please upload the exact Excel the system produced.";
const NO_EMBEDDED_DATA_ERROR =
  "This file doesn't contain the data this system needs to re-import it (it may have been generated before this feature was added). Please re-enter the details manually.";
const CORRUPT_FILE_ERROR = "Couldn't read this Excel file — it may be corrupted. Please try uploading it again.";

export interface ImportRequestResponseBody {
  header: TravelRequestImportPayload["header"];
  trips: TravelRequestImportPayload["trips"];
  submissionNumber: number;
}

export async function POST(request: Request): Promise<NextResponse> {
  let file: File;
  try {
    const form = await request.formData();
    const f = form.get("file");
    if (!(f instanceof File)) {
      return NextResponse.json({ error: "No file provided" }, { status: 400 });
    }
    file = f;
  } catch {
    return NextResponse.json({ error: "Invalid request body" }, { status: 400 });
  }

  const parsedName = parseSubmissionFileName(file.name, "TR");
  if (!parsedName) {
    return NextResponse.json({ error: BAD_FILENAME_ERROR }, { status: 400 });
  }

  let wb: ExcelJS.Workbook;
  try {
    const buffer = Buffer.from(await file.arrayBuffer());
    wb = new ExcelJS.Workbook();
    // exceljs's own index.d.ts (line 1) declares a global `interface Buffer extends ArrayBuffer
    // {}`, which merges into -- and corrupts -- Node's real ambient Buffer type by additionally
    // demanding ArrayBuffer-only members (resizable/maxByteLength/etc, from modern lib.esnext)
    // that no real Buffer.from() result has. writeBuffer()'s return side is unaffected (Buffer.
    // from() accepts the wider ArrayBufferLike shape), but load()'s input side breaks for any
    // real Buffer -- an upstream typing bug, not a real runtime mismatch.
    // @ts-expect-error -- see comment above; buffer is a genuine Node Buffer at runtime.
    await wb.xlsx.load(buffer);
  } catch (e) {
    console.error("[travel-import] step=load error", e);
    return NextResponse.json({ error: CORRUPT_FILE_ERROR }, { status: 400 });
  }

  const payload = readJsonSheet<TravelRequestImportPayload>(wb);
  if (!payload) {
    return NextResponse.json({ error: NO_EMBEDDED_DATA_ERROR }, { status: 422 });
  }

  const body: ImportRequestResponseBody = {
    header: payload.header,
    trips: payload.trips,
    submissionNumber: parsedName.submissionNumber,
  };
  return NextResponse.json(body);
}
